from app.core.logging import structured_logger as logger
from app.services.nlp.model import get_nlp


_SKILLS_WHITELIST: dict[str, str] = {
    # ── Programming Languages ──
    "python": "Python",
    "java": "Java",
    "javascript": "JavaScript",
    "typescript": "TypeScript",
    "go": "Go",
    "golang": "Go",
    "rust": "Rust",
    "swift": "Swift",
    "kotlin": "Kotlin",
    "ruby": "Ruby",
    "scala": "Scala",
    "php": "PHP",
    "perl": "Perl",
    "r": "R",
    "matlab": "MATLAB",
    "c": "C",
    "c++": "C++",
    "c#": "C#",
    "dart": "Dart",
    "elixir": "Elixir",
    "haskell": "Haskell",
    "lua": "Lua",
    "groovy": "Groovy",
    "bash": "Bash",
    "shell": "Shell",
    "powershell": "PowerShell",
    "cobol": "COBOL",
    "fortran": "Fortran",
    "objective-c": "Objective-C",
    "assembly": "Assembly",
    "solidity": "Solidity",
    "vba": "VBA",
    "visual basic": "Visual Basic",
    "vb.net": "VB.NET",
    "f#": "F#",
    "clojure": "Clojure",
    "erlang": "Erlang",
    "julia": "Julia",
    "zig": "Zig",
    "nim": "Nim",
    # ── Frontend Frameworks & Libraries ──
    "react": "React",
    "reactjs": "React",
    "angular": "Angular",
    "vue": "Vue.js",
    "vuejs": "Vue.js",
    "svelte": "Svelte",
    "nextjs": "Next.js",
    "next.js": "Next.js",
    "nuxtjs": "Nuxt.js",
    "nuxt.js": "Nuxt.js",
    "remix": "Remix",
    "gatsby": "Gatsby",
    "astro": "Astro",
    "solidjs": "SolidJS",
    "htmx": "HTMX",
    "alpine.js": "Alpine.js",
    "tailwind": "Tailwind CSS",
    "tailwindcss": "Tailwind CSS",
    "bootstrap": "Bootstrap",
    "material ui": "Material UI",
    "chakra ui": "Chakra UI",
    "ant design": "Ant Design",
    "shadcn": "shadcn/ui",
    "radix": "Radix UI",
    "storybook": "Storybook",
    # ── CSS & Styling ──
    "html": "HTML",
    "html5": "HTML5",
    "css": "CSS",
    "css3": "CSS3",
    "sass": "SASS",
    "scss": "SCSS",
    "less": "Less",
    "styled components": "Styled Components",
    "postcss": "PostCSS",
    "emotion": "Emotion",
    # ── Backend Frameworks ──
    "fastapi": "FastAPI",
    "django": "Django",
    "flask": "Flask",
    "express": "Express.js",
    "expressjs": "Express.js",
    "nestjs": "NestJS",
    "fastify": "Fastify",
    "koa": "Koa.js",
    "hono": "Hono",
    "spring": "Spring",
    "springboot": "Spring Boot",
    "spring boot": "Spring Boot",
    "rails": "Ruby on Rails",
    "laravel": "Laravel",
    "symfony": "Symfony",
    "gin": "Gin",
    "fiber": "Fiber",
    "actix": "Actix",
    "asp.net": "ASP.NET",
    "blazor": "Blazor",
    ".net": ".NET",
    "dotnet": ".NET",
    "phoenix": "Phoenix",
    "quarkus": "Quarkus",
    "micronaut": "Micronaut",
    "hapi": "Hapi.js",
    # ── Mobile Development ──
    "react native": "React Native",
    "flutter": "Flutter",
    "expo": "Expo",
    "ionic": "Ionic",
    "xamarin": "Xamarin",
    "maui": ".NET MAUI",
    "swiftui": "SwiftUI",
    "jetpack compose": "Jetpack Compose",
    "kotlin multiplatform": "Kotlin Multiplatform",
    "capacitor": "Capacitor",
    # ── Databases ──
    "postgresql": "PostgreSQL",
    "postgres": "PostgreSQL",
    "mysql": "MySQL",
    "mariadb": "MariaDB",
    "mongodb": "MongoDB",
    "redis": "Redis",
    "elasticsearch": "Elasticsearch",
    "cassandra": "Cassandra",
    "dynamodb": "DynamoDB",
    "firestore": "Firestore",
    "sqlite": "SQLite",
    "oracle": "Oracle DB",
    "mssql": "SQL Server",
    "sql server": "SQL Server",
    "neo4j": "Neo4j",
    "influxdb": "InfluxDB",
    "sql": "SQL",
    "nosql": "NoSQL",
    "supabase": "Supabase",
    "firebase": "Firebase",
    "planetscale": "Planetscale",
    "cockroachdb": "CockroachDB",
    "timescaledb": "TimescaleDB",
    "snowflake": "Snowflake",
    "bigquery": "BigQuery",
    "redshift": "Redshift",
    "clickhouse": "ClickHouse",
    # ── Cloud Platforms ──
    "aws": "AWS",
    "amazon web services": "AWS",
    "gcp": "GCP",
    "google cloud": "Google Cloud",
    "azure": "Azure",
    "microsoft azure": "Microsoft Azure",
    "digitalocean": "DigitalOcean",
    "heroku": "Heroku",
    "vercel": "Vercel",
    "netlify": "Netlify",
    "cloudflare": "Cloudflare",
    "huawei cloud": "Huawei Cloud",
    "alibaba cloud": "Alibaba Cloud",
    "aliyun": "Alibaba Cloud",
    "oracle cloud": "Oracle Cloud",
    # ── DevOps & Infrastructure ──
    "docker": "Docker",
    "kubernetes": "Kubernetes",
    "k8s": "Kubernetes",
    "terraform": "Terraform",
    "ansible": "Ansible",
    "helm": "Helm",
    "jenkins": "Jenkins",
    "github actions": "GitHub Actions",
    "gitlab ci": "GitLab CI",
    "gitlab": "GitLab",
    "circleci": "CircleCI",
    "travis": "Travis CI",
    "nginx": "Nginx",
    "apache": "Apache",
    "linux": "Linux",
    "unix": "Unix",
    "ubuntu": "Ubuntu",
    "centos": "CentOS",
    "debian": "Debian",
    "git": "Git",
    "github": "GitHub",
    "bitbucket": "Bitbucket",
    "ci/cd": "CI/CD",
    "cicd": "CI/CD",
    "vagrant": "Vagrant",
    "packer": "Packer",
    "consul": "Consul",
    "istio": "Istio",
    "argocd": "ArgoCD",
    "pulumi": "Pulumi",
    "datadog": "Datadog",
    "newrelic": "New Relic",
    "splunk": "Splunk",
    "cloudformation": "AWS CloudFormation",
    "serverless": "Serverless",
    # ── Data Science & ML ──
    "pandas": "Pandas",
    "numpy": "NumPy",
    "scipy": "SciPy",
    "matplotlib": "Matplotlib",
    "seaborn": "Seaborn",
    "plotly": "Plotly",
    "tensorflow": "TensorFlow",
    "pytorch": "PyTorch",
    "keras": "Keras",
    "scikit-learn": "Scikit-learn",
    "sklearn": "Scikit-learn",
    "xgboost": "XGBoost",
    "lightgbm": "LightGBM",
    "catboost": "CatBoost",
    "huggingface": "Hugging Face",
    "langchain": "LangChain",
    "llamaindex": "LlamaIndex",
    "spark": "Apache Spark",
    "hadoop": "Hadoop",
    "kafka": "Kafka",
    "airflow": "Apache Airflow",
    "dbt": "dbt",
    "mlflow": "MLflow",
    "wandb": "Weights & Biases",
    "dvc": "DVC",
    "streamlit": "Streamlit",
    "gradio": "Gradio",
    "jupyter": "Jupyter",
    "opencv": "OpenCV",
    "pillow": "Pillow",
    # ── Data Visualization & BI ──
    "tableau": "Tableau",
    "powerbi": "Power BI",
    "power bi": "Power BI",
    "looker": "Looker",
    "metabase": "Metabase",
    "google analytics": "Google Analytics",
    "google analytics 4": "Google Analytics 4",
    "ga4": "GA4",
    "adobe analytics": "Adobe Analytics",
    "mixpanel": "Mixpanel",
    "amplitude": "Amplitude",
    # ── AI / ML Concepts ──
    "machine learning": "Machine Learning",
    "deep learning": "Deep Learning",
    "natural language processing": "NLP",
    "nlp": "NLP",
    "computer vision": "Computer Vision",
    "data engineering": "Data Engineering",
    "data science": "Data Science",
    "data analysis": "Data Analysis",
    "data analytics": "Data Analytics",
    "big data": "Big Data",
    "data mining": "Data Mining",
    "reinforcement learning": "Reinforcement Learning",
    "generative ai": "Generative AI",
    "gen ai": "Gen AI",
    "genai": "GenAI",
    "llm": "Large Language Models",
    "large language models": "Large Language Models",
    "rag": "RAG",
    "retrieval augmented generation": "RAG",
    "prompt engineering": "Prompt Engineering",
    "ai agent": "AI Agents",
    "ai agents": "AI Agents",
    "mcp": "MCP",
    "model context protocol": "Model Context Protocol",
    "fine-tuning": "Fine-Tuning",
    "transfer learning": "Transfer Learning",
    "feature engineering": "Feature Engineering",
    "a/b testing": "A/B Testing",
    "ab testing": "A/B Testing",
    # ── API & Architecture ──
    "rest": "REST API",
    "restful": "REST API",
    "rest api": "REST API",
    "grpc": "gRPC",
    "graphql": "GraphQL",
    "websocket": "WebSocket",
    "microservices": "Microservices",
    "event driven": "Event-Driven Architecture",
    "message queue": "Message Queue",
    "soa": "SOA",
    "api gateway": "API Gateway",
    "service mesh": "Service Mesh",
    "event sourcing": "Event Sourcing",
    "cqrs": "CQRS",
    # ── Methodologies ──
    "agile": "Agile",
    "scrum": "Scrum",
    "kanban": "Kanban",
    "devops": "DevOps",
    "mlops": "MLOps",
    "devsecops": "DevSecOps",
    "tdd": "TDD",
    "bdd": "BDD",
    "ddd": "Domain-Driven Design",
    "clean architecture": "Clean Architecture",
    "system design": "System Design",
    "object oriented": "OOP",
    "oop": "OOP",
    "functional programming": "Functional Programming",
    "sprint": "Sprint Planning",
    "waterfall": "Waterfall",
    "prince2": "PRINCE2",
    "six sigma": "Six Sigma",
    "lean": "Lean",
    "itil": "ITIL",
    "sre": "SRE",
    "site reliability engineering": "SRE",
    # ── Project Management & Collaboration ──
    "jira": "Jira",
    "confluence": "Confluence",
    "notion": "Notion",
    "asana": "Asana",
    "trello": "Trello",
    "monday.com": "Monday.com",
    "slack": "Slack",
    "microsoft teams": "Microsoft Teams",
    "linear": "Linear",
    "clickup": "ClickUp",
    "basecamp": "Basecamp",
    "ms project": "MS Project",
    "pmp": "PMP",
    "pmp certification": "PMP",
    "prince2 certification": "PRINCE2",
    "csm": "CSM",
    "safe": "SAFe",
    # ── Design Tools ──
    "figma": "Figma",
    "sketch": "Sketch",
    "adobe xd": "Adobe XD",
    "adobe photoshop": "Adobe Photoshop",
    "photoshop": "Adobe Photoshop",
    "adobe illustrator": "Adobe Illustrator",
    "illustrator": "Adobe Illustrator",
    "adobe after effects": "Adobe After Effects",
    "after effects": "Adobe After Effects",
    "adobe premiere": "Adobe Premiere Pro",
    "premiere pro": "Adobe Premiere Pro",
    "indesign": "Adobe InDesign",
    "canva": "Canva",
    "invision": "InVision",
    "zeplin": "Zeplin",
    "framer": "Framer",
    "miro": "Miro",
    "lucidchart": "Lucidchart",
    "whimsical": "Whimsical",
    "blender": "Blender",
    # ── Testing Tools ──
    "postman": "Postman",
    "swagger": "Swagger",
    "openapi": "OpenAPI",
    "selenium": "Selenium",
    "cypress": "Cypress",
    "playwright": "Playwright",
    "jest": "Jest",
    "vitest": "Vitest",
    "pytest": "pytest",
    "junit": "JUnit",
    "mocha": "Mocha",
    "chai": "Chai",
    "cucumber": "Cucumber",
    "k6": "k6",
    "jmeter": "JMeter",
    "locust": "Locust",
    "pylint": "Pylint",
    "eslint": "ESLint",
    "ruff": "Ruff",
    # ── Messaging & Queuing ──
    "celery": "Celery",
    "rabbitmq": "RabbitMQ",
    "apache pulsar": "Apache Pulsar",
    "amazon sqs": "Amazon SQs",
    "google pub/sub": "Google Pub/Sub",
    # ── Monitoring & Observability ──
    "prometheus": "Prometheus",
    "grafana": "Grafana",
    "sentry": "Sentry",
    "elk stack": "ELK Stack",
    "elastic stack": "Elastic Stack",
    "loki": "Loki",
    "jaeger": "Jaeger",
    "opentelemetry": "OpenTelemetry",
    "zipkin": "Zipkin",
    # ── Security ──
    "cybersecurity": "Cybersecurity",
    "penetration testing": "Penetration Testing",
    "pentesting": "Penetration Testing",
    "owasp": "OWASP",
    "ssl/tls": "SSL/TLS",
    "oauth": "OAuth",
    "jwt": "JWT",
    "sso": "SSO",
    "saml": "SAML",
    "encryption": "Encryption",
    "information security": "Information Security",
    "kali linux": "Kali Linux",
    "burp suite": "Burp Suite",
    "wireshark": "Wireshark",
    " Nessus": "Nessus",
    "sonarqube": "SonarQube",
    "sast": "SAST",
    "dast": "DAST",
    # ── ERP & Business Systems ──
    "sap": "SAP",
    "oracle erp": "Oracle ERP",
    "microsoft dynamics": "Microsoft Dynamics",
    "salesforce": "Salesforce",
    "hubspot": "HubSpot",
    "zoho": "Zoho",
    "workday": "Workday",
    "peoplesoft": "PeopleSoft",
    "odoo": "Odoo",
    # ── Marketing & SEO ──
    "seo": "SEO",
    "search engine optimization": "SEO",
    "sem": "SEM",
    "google ads": "Google Ads",
    "google adwords": "Google Ads",
    "facebook ads": "Facebook Ads",
    "meta ads": "Meta Ads",
    "tiktok ads": "TikTok Ads",
    "linkedin ads": "LinkedIn Ads",
    "semrush": "SEMrush",
    "ahrefs": "Ahrefs",
    "moz": "Moz",
    "google search console": "Google Search Console",
    "mailchimp": "Mailchimp",
    "hubspot marketing": "HubSpot Marketing",
    "hootsuite": "Hootsuite",
    "buffer": "Buffer",
    "sprout social": "Sprout Social",
    "social media marketing": "Social Media Marketing",
    "content marketing": "Content Marketing",
    "email marketing": "Email Marketing",
    "inbound marketing": "Inbound Marketing",
    "marketing automation": "Marketing Automation",
    "google tag manager": "Google Tag Manager",
    "gtm": "GTM",
    "conversion rate optimization": "CRO",
    "cro": "CRO",
    # ── E-Commerce & Marketplace (Indonesia) ──
    "shopee": "Shopee",
    "tokopedia": "Tokopedia",
    "lazada": "Lazada",
    "bukalapak": "Bukalapak",
    "blibli": "Blibli",
    "tiktok shop": "TikTok Shop",
    "woocommerce": "WooCommerce",
    "shopify": "Shopify",
    "magento": "Magento",
    "prestashop": "PrestaShop",
    "opencart": "OpenCart",
    "marketplace": "Marketplace",
    "e-commerce": "E-Commerce",
    "ecommerce": "E-Commerce",
    "dropship": "Dropship",
    "dropshipping": "Dropshipping",
    "fulfillment": "Fulfillment",
    "product listing": "Product Listing",
    "catalog management": "Catalog Management",
    "payment gateway": "Payment Gateway",
    "midtrans": "Midtrans",
    "xendit": "Xendit",
    "doku": "DOKU",
    "ovo": "OVO",
    "gopay": "GoPay",
    "dana": "DANA",
    "linkaja": "LinkAja",
    "qris": "QRIS",
    # ── Indonesian Tech Ecosystem ──
    "gojek": "Gojek",
    "grab": "Grab",
    "traveloka": "Traveloka",
    "flip": "Flip",
    "ajaib": "Ajaib",
    "stockbit": "Stockbit",
    "bibit": "Bibit",
    "ruangguru": "Ruangguru",
    "zenius": "Zenius",
    "halodoc": "Halodoc",
    "alodokter": "Alodokter",
    "kumparan": "Kumparan",
    "detik": "Detik.com",
    "kompas": "Kompas",
    # ── Fintech & Banking ──
    "fintech": "Fintech",
    "financial technology": "Fintech",
    "blockchain": "Blockchain",
    "web3": "Web3",
    "cryptocurrency": "Cryptocurrency",
    "smart contract": "Smart Contracts",
    "defi": "DeFi",
    "nft": "NFT",
    "digital banking": "Digital Banking",
    "digital payment": "Digital Payment",
    "e-wallet": "E-Wallet",
    "digital wallet": "Digital Wallet",
    "peer to peer lending": "P2P Lending",
    "p2p lending": "P2P Lending",
    "crowdfunding": "Crowdfunding",
    "insurtech": "Insurtech",
    "regtech": "Regtech",
    # ── Productivity & Office ──
    "microsoft office": "Microsoft Office",
    "ms office": "Microsoft Office",
    "microsoft excel": "Microsoft Excel",
    "excel": "Microsoft Excel",
    "microsoft word": "Microsoft Word",
    "microsoft powerpoint": "Microsoft PowerPoint",
    "powerpoint": "Microsoft PowerPoint",
    "sharepoint": "SharePoint",
    "google workspace": "Google Workspace",
    "gsuite": "Google Workspace",
    "google docs": "Google Docs",
    "google sheets": "Google Sheets",
    "google slides": "Google Slides",
    "spreadsheets": "Spreadsheets",
    # ── Operating Systems ──
    "macos": "macOS",
    "windows": "Windows",
    "windows server": "Windows Server",
    "android": "Android",
    "ios": "iOS",
    # ── Soft Skills ──
    "leadership": "Leadership",
    "team leadership": "Team Leadership",
    "teamwork": "Teamwork",
    "communication": "Communication",
    "communication skills": "Communication Skills",
    "public speaking": "Public Speaking",
    "presentation skills": "Presentation Skills",
    "problem solving": "Problem Solving",
    "critical thinking": "Critical Thinking",
    "analytical thinking": "Analytical Thinking",
    "analytical skills": "Analytical Skills",
    "time management": "Time Management",
    "project management": "Project Management",
    "program management": "Program Management",
    "change management": "Change Management",
    "risk management": "Risk Management",
    "stakeholder management": "Stakeholder Management",
    "conflict resolution": "Conflict Resolution",
    "negotiation": "Negotiation",
    "decision making": "Decision Making",
    "strategic planning": "Strategic Planning",
    "strategic thinking": "Strategic Thinking",
    "business strategy": "Business Strategy",
    "business development": "Business Development",
    "business analysis": "Business Analysis",
    "business intelligence": "Business Intelligence",
    "cross functional": "Cross-Functional Collaboration",
    "cross-functional team": "Cross-Functional Team",
    "client management": "Client Management",
    "client relations": "Client Relations",
    "customer service": "Customer Service",
    "customer success": "Customer Success",
    "customer experience": "Customer Experience",
    "user experience": "User Experience",
    "ux": "UX",
    "ui": "UI",
    "user interface": "User Interface",
    "ux research": "UX Research",
    "user research": "User Research",
    "wireframing": "Wireframing",
    "prototyping": "Prototyping",
    "responsive design": "Responsive Design",
    "design thinking": "Design Thinking",
    "product management": "Product Management",
    "product design": "Product Design",
    "product development": "Product Development",
    "mentoring": "Mentoring",
    "coaching": "Coaching",
    "training": "Training",
    "facilitation": "Facilitation",
    "adaptability": "Adaptability",
    "creativity": "Creativity",
    "innovation": "Innovation",
    "emotional intelligence": "Emotional Intelligence",
    "attention to detail": "Attention to Detail",
    "multitasking": "Multitasking",
    "collaboration": "Collaboration",
    "remote work": "Remote Work",
    "remote collaboration": "Remote Collaboration",
    "continuous learning": "Continuous Learning",
    "self-motivated": "Self-Motivated",
    "empathy": "Empathy",
    "interpersonal skills": "Interpersonal Skills",
    "organizational skills": "Organizational Skills",
    "work under pressure": "Work Under Pressure",
    # ── Finance & Accounting ──
    "financial analysis": "Financial Analysis",
    "financial modeling": "Financial Modeling",
    "financial reporting": "Financial Reporting",
    "financial planning": "Financial Planning",
    "budgeting": "Budgeting",
    "budget management": "Budget Management",
    "forecasting": "Forecasting",
    "accounting": "Accounting",
    "auditing": "Auditing",
    "taxation": "Taxation",
    "payroll": "Payroll",
    "invoicing": "Invoicing",
    "bookkeeping": "Bookkeeping",
    "gaap": "GAAP",
    "psak": "PSAK",
    "ifrs": "IFRS",
    "cash flow": "Cash Flow Management",
    "cost analysis": "Cost Analysis",
    "revenue growth": "Revenue Growth",
    "portfolio management": "Portfolio Management",
    "investment analysis": "Investment Analysis",
    "due diligence": "Due Diligence",
    "compliance": "Compliance",
    "regulatory compliance": "Regulatory Compliance",
    "risk assessment": "Risk Assessment",
    # ── HR & People ──
    "human resources": "Human Resources",
    "hr": "Human Resources",
    "recruitment": "Recruitment",
    "talent acquisition": "Talent Acquisition",
    "talent management": "Talent Management",
    "performance management": "Performance Management",
    "employee engagement": "Employee Engagement",
    "onboarding": "Onboarding",
    "learning and development": "Learning & Development",
    "l&d": "Learning & Development",
    "organizational development": "Organizational Development",
    "compensation and benefits": "Compensation & Benefits",
    "employee relations": "Employee Relations",
    "succession planning": "Succession Planning",
    # ── Operations & Supply Chain ──
    "operations management": "Operations Management",
    "supply chain": "Supply Chain",
    "supply chain management": "Supply Chain Management",
    "logistics": "Logistics",
    "procurement": "Procurement",
    "vendor management": "Vendor Management",
    "inventory management": "Inventory Management",
    "warehouse management": "Warehouse Management",
    "quality assurance": "Quality Assurance",
    "qa": "QA",
    "quality control": "Quality Control",
    "qc": "QC",
    "process improvement": "Process Improvement",
    "continuous improvement": "Continuous Improvement",
    "lean six sigma": "Lean Six Sigma",
    "iso": "ISO",
    "iso 9001": "ISO 9001",
    "sop": "SOP",
    "standard operating procedures": "Standard Operating Procedures",
    # ── Education & Training ──
    "teaching": "Teaching",
    "curriculum development": "Curriculum Development",
    "e-learning": "E-Learning",
    "instructional design": "Instructional Design",
    "learning management system": "LMS",
    "lms": "LMS",
    "moodle": "Moodle",
    "canvas lms": "Canvas LMS",
    # ── Healthcare ──
    "healthcare": "Healthcare",
    "telemedicine": "Telemedicine",
    "medical coding": "Medical Coding",
    "clinical data": "Clinical Data",
    "hipaa": "HIPAA",
    "patient care": "Patient Care",
    "nursing": "Nursing",
    "pharmaceutical": "Pharmaceutical",
    # ── Legal & Compliance ──
    "legal": "Legal",
    "contract management": "Contract Management",
    "litigation": "Litigation",
    "corporate law": "Corporate Law",
    "intellectual property": "Intellectual Property",
    "data privacy": "Data Privacy",
    "gdpr": "GDPR",
    "pdpa": "PDPA",
    "pdp law": "PDP Law (Indonesia)",
    # ── Indonesia-Specific Certifications ──
    "bnsp": "BNSP Certification",
    "tuk": "TUK Certification",
    "lsp": "LSP Certification",
    "kominfo": "Kominfo Certification",
    "cloud practitioner": "AWS Cloud Practitioner",
    "aws solutions architect": "AWS Solutions Architect",
    "aws certified": "AWS Certified",
    "azure fundamentals": "Azure Fundamentals",
    "gcp certified": "GCP Certified",
    "google certified": "Google Certified",
    "scrum master": "Scrum Master",
    "product owner": "Product Owner",
    "togaf": "TOGAF",
    # ── Content & Media ──
    "content writing": "Content Writing",
    "copywriting": "Copywriting",
    "technical writing": "Technical Writing",
    "graphic design": "Graphic Design",
    "video editing": "Video Editing",
    "video production": "Video Production",
    "photography": "Photography",
    "photo editing": "Photo Editing",
    "social media": "Social Media",
    "social media management": "Social Media Management",
    "digital marketing": "Digital Marketing",
    "content strategy": "Content Strategy",
    "brand management": "Brand Management",
    "branding": "Branding",
    "public relations": "Public Relations",
    "pr": "Public Relations",
    "journalism": "Journalism",
    "editing": "Editing",
    "publishing": "Publishing",
    "podcast": "Podcast Production",
    # ── Networking & Infrastructure ──
    "networking": "Networking",
    "cisco": "Cisco",
    "ccna": "CCNA",
    "ccnp": "CCNP",
    "dns": "DNS",
    "vpn": "VPN",
    "lan": "LAN",
    "wan": "WAN",
    "tcp/ip": "TCP/IP",
    "firewall": "Firewall",
    "load balancing": "Load Balancing",
    "cdn": "CDN",
    # ── Version Control & Build ──
    "webpack": "Webpack",
    "vite": "Vite",
    "babel": "Babel",
    "rollup": "Rollup",
    "esbuild": "esbuild",
    "parcel": "Parcel",
    "turbopack": "Turbopack",
    "npm": "npm",
    "yarn": "Yarn",
    "pnpm": "pnpm",
    "bun": "Bun",
    "pip": "pip",
    "conda": "Conda",
    "poetry": "Poetry",
    "uv": "uv",
    "maven": "Maven",
    "gradle": "Gradle",
    "nuget": "NuGet",
    # ── CMS & Platforms ──
    "wordpress": "WordPress",
    "drupal": "Drupal",
    "contentful": "Contentful",
    "strapi": "Strapi",
    "sanity": "Sanity",
    "webflow": "Webflow",
    "squarespace": "Squarespace",
    "wix": "Wix",
    "elementor": "Elementor",
    # ── Other In-Demand Skills ──
    "sustainability": "Sustainability",
    "esg": "ESG",
    "green technology": "Green Technology",
    "digital transformation": "Digital Transformation",
    "automation": "Automation",
    "rpa": "RPA",
    "robotic process automation": "RPA",
    "power automate": "Power Automate",
    "zapier": "Zapier",
    "n8n": "n8n",
    "make": "Make (Integromat)",
    "low-code": "Low-Code",
    "no-code": "No-Code",
    "iot": "IoT",
    "internet of things": "IoT",
    "embedded systems": "Embedded Systems",
    "arduino": "Arduino",
    "raspberry pi": "Raspberry Pi",
    "game development": "Game Development",
    "unity": "Unity",
    "unreal engine": "Unreal Engine",
    "godot": "Godot",
    "3d modeling": "3D Modeling",
    "vr": "VR",
    "ar": "AR",
    "augmented reality": "Augmented Reality",
    "virtual reality": "Virtual Reality",
    "metaverse": "Metaverse",
}


_WHITELIST_LOWER: dict[str, str] = {k.lower(): v for k, v in _SKILLS_WHITELIST.items()}


_MAX_NGRAM = max(len(k.split()) for k in _SKILLS_WHITELIST)


def extract_skills(text: str, score_cutoff: int = 85) -> list[str]:  # noqa: ARG001
    nlp = get_nlp()
    doc = nlp(text)

    tokens = [token.text for token in doc if not token.is_space]
    matched: set[str] = set()
    covered: set[int] = set()

    for ngram_len in range(_MAX_NGRAM, 0, -1):
        for i in range(len(tokens) - ngram_len + 1):

            if any(j in covered for j in range(i, i + ngram_len)):
                continue
            phrase = " ".join(tokens[i : i + ngram_len]).lower().strip(".,;:()")
            if phrase in _WHITELIST_LOWER:
                matched.add(_WHITELIST_LOWER[phrase])
                for j in range(i, i + ngram_len):
                    covered.add(j)

    logger.info("skill_extraction_done", count=len(matched))
    return sorted(matched)
