from app.core.logging import structured_logger as logger
from app.services.nlp.model import get_nlp


_SKILLS_WHITELIST: dict[str, str] = {
    "python": "Python",
    "java": "Java",
    "javascript": "JavaScript",
    "typescript": "TypeScript",
    "go": "Go",
    "golang": "Go",
    "rust": "Rust",
    "swift": "Swift",
    "kotlin": "Kotlin",
    "ruby": "Ruby",
    "scala": "Scala",
    "php": "PHP",
    "perl": "Perl",
    "r": "R",
    "matlab": "MATLAB",
    "c": "C",
    "c++": "C++",
    "c#": "C#",
    "dart": "Dart",
    "elixir": "Elixir",
    "haskell": "Haskell",
    "lua": "Lua",
    "groovy": "Groovy",
    "bash": "Bash",
    "shell": "Shell",
    "powershell": "PowerShell",
    "cobol": "COBOL",
    "fortran": "Fortran",
    "react": "React",
    "angular": "Angular",
    "vue": "Vue.js",
    "svelte": "Svelte",
    "nextjs": "Next.js",
    "next.js": "Next.js",
    "nuxtjs": "Nuxt.js",
    "remix": "Remix",
    "gatsby": "Gatsby",
    "html": "HTML",
    "css": "CSS",
    "sass": "SASS",
    "scss": "SCSS",
    "tailwind": "Tailwind CSS",
    "bootstrap": "Bootstrap",
    "webpack": "Webpack",
    "vite": "Vite",
    "babel": "Babel",
    "jquery": "jQuery",
    "redux": "Redux",
    "graphql": "GraphQL",
    "fastapi": "FastAPI",
    "django": "Django",
    "flask": "Flask",
    "express": "Express.js",
    "nestjs": "NestJS",
    "fastify": "Fastify",
    "spring": "Spring",
    "springboot": "Spring Boot",
    "spring boot": "Spring Boot",
    "rails": "Ruby on Rails",
    "laravel": "Laravel",
    "symfony": "Symfony",
    "gin": "Gin",
    "fiber": "Fiber",
    "actix": "Actix",
    "postgresql": "PostgreSQL",
    "postgres": "PostgreSQL",
    "mysql": "MySQL",
    "mariadb": "MariaDB",
    "mongodb": "MongoDB",
    "redis": "Redis",
    "elasticsearch": "Elasticsearch",
    "cassandra": "Cassandra",
    "dynamodb": "DynamoDB",
    "firestore": "Firestore",
    "sqlite": "SQLite",
    "oracle": "Oracle DB",
    "mssql": "SQL Server",
    "sql server": "SQL Server",
    "neo4j": "Neo4j",
    "influxdb": "InfluxDB",
    "sql": "SQL",
    "nosql": "NoSQL",
    "aws": "AWS",
    "gcp": "GCP",
    "azure": "Azure",
    "docker": "Docker",
    "kubernetes": "Kubernetes",
    "k8s": "Kubernetes",
    "terraform": "Terraform",
    "ansible": "Ansible",
    "helm": "Helm",
    "jenkins": "Jenkins",
    "github actions": "GitHub Actions",
    "gitlab": "GitLab",
    "circleci": "CircleCI",
    "travis": "Travis CI",
    "nginx": "Nginx",
    "apache": "Apache",
    "linux": "Linux",
    "unix": "Unix",
    "ubuntu": "Ubuntu",
    "git": "Git",
    "github": "GitHub",
    "bitbucket": "Bitbucket",
    "ci/cd": "CI/CD",
    "cicd": "CI/CD",
    "pandas": "Pandas",
    "numpy": "NumPy",
    "scipy": "SciPy",
    "matplotlib": "Matplotlib",
    "seaborn": "Seaborn",
    "tensorflow": "TensorFlow",
    "pytorch": "PyTorch",
    "keras": "Keras",
    "scikit-learn": "Scikit-learn",
    "sklearn": "Scikit-learn",
    "xgboost": "XGBoost",
    "lightgbm": "LightGBM",
    "huggingface": "Hugging Face",
    "langchain": "LangChain",
    "spark": "Apache Spark",
    "hadoop": "Hadoop",
    "kafka": "Kafka",
    "airflow": "Apache Airflow",
    "dbt": "dbt",
    "tableau": "Tableau",
    "powerbi": "Power BI",
    "power bi": "Power BI",
    "looker": "Looker",
    "machine learning": "Machine Learning",
    "deep learning": "Deep Learning",
    "natural language processing": "NLP",
    "nlp": "NLP",
    "computer vision": "Computer Vision",
    "data engineering": "Data Engineering",
    "data science": "Data Science",
    "rest": "REST API",
    "restful": "REST API",
    "rest api": "REST API",
    "grpc": "gRPC",
    "websocket": "WebSocket",
    "microservices": "Microservices",
    "event driven": "Event-Driven Architecture",
    "message queue": "Message Queue",
    "agile": "Agile",
    "scrum": "Scrum",
    "kanban": "Kanban",
    "devops": "DevOps",
    "mlops": "MLOps",
    "devsecops": "DevSecOps",
    "tdd": "TDD",
    "bdd": "BDD",
    "ddd": "Domain-Driven Design",
    "clean architecture": "Clean Architecture",
    "system design": "System Design",
    "object oriented": "OOP",
    "oop": "OOP",
    "functional programming": "Functional Programming",
    "jira": "Jira",
    "confluence": "Confluence",
    "notion": "Notion",
    "figma": "Figma",
    "postman": "Postman",
    "swagger": "Swagger",
    "openapi": "OpenAPI",
    "celery": "Celery",
    "rabbitmq": "RabbitMQ",
    "prometheus": "Prometheus",
    "grafana": "Grafana",
    "sentry": "Sentry",
    "datadog": "Datadog",
}


_WHITELIST_LOWER: dict[str, str] = {k.lower(): v for k, v in _SKILLS_WHITELIST.items()}


_MAX_NGRAM = max(len(k.split()) for k in _SKILLS_WHITELIST)


def extract_skills(text: str, score_cutoff: int = 85) -> list[str]:  # noqa: ARG001
    nlp = get_nlp()
    doc = nlp(text)

    tokens = [token.text for token in doc if not token.is_space]
    matched: set[str] = set()
    covered: set[int] = set()

    for ngram_len in range(_MAX_NGRAM, 0, -1):
        for i in range(len(tokens) - ngram_len + 1):

            if any(j in covered for j in range(i, i + ngram_len)):
                continue
            phrase = " ".join(tokens[i : i + ngram_len]).lower().strip(".,;:()")
            if phrase in _WHITELIST_LOWER:
                matched.add(_WHITELIST_LOWER[phrase])
                for j in range(i, i + ngram_len):
                    covered.add(j)

    logger.info("skill_extraction_done", count=len(matched))
    return sorted(matched)
