from app.core.logging import structured_logger as logger
from app.services.nlp.model import get_nlp

try:
    from rapidfuzz import fuzz as _fuzz

    _FUZZY_AVAILABLE = True
except ImportError:
    _fuzz = None
    _FUZZY_AVAILABLE = False


_SKILLS_WHITELIST: dict[str, str] = {
    # ── Programming Languages ──
    "python": "Python",
    "java": "Java",
    "javascript": "JavaScript",
    "typescript": "TypeScript",
    "go": "Go",
    "golang": "Go",
    "rust": "Rust",
    "swift": "Swift",
    "kotlin": "Kotlin",
    "ruby": "Ruby",
    "scala": "Scala",
    "php": "PHP",
    "perl": "Perl",
    "r": "R",
    "matlab": "MATLAB",
    "c": "C",
    "c++": "C++",
    "c#": "C#",
    "dart": "Dart",
    "elixir": "Elixir",
    "haskell": "Haskell",
    "lua": "Lua",
    "groovy": "Groovy",
    "bash": "Bash",
    "shell": "Shell",
    "powershell": "PowerShell",
    "cobol": "COBOL",
    "fortran": "Fortran",
    "objective-c": "Objective-C",
    "assembly": "Assembly",
    "solidity": "Solidity",
    "vba": "VBA",
    "visual basic": "Visual Basic",
    "vb.net": "VB.NET",
    "f#": "F#",
    "clojure": "Clojure",
    "erlang": "Erlang",
    "julia": "Julia",
    "zig": "Zig",
    "nim": "Nim",
    # ── Frontend Frameworks & Libraries ──
    "react": "React",
    "reactjs": "React",
    "angular": "Angular",
    "vue": "Vue.js",
    "vuejs": "Vue.js",
    "svelte": "Svelte",
    "nextjs": "Next.js",
    "next.js": "Next.js",
    "nuxtjs": "Nuxt.js",
    "nuxt.js": "Nuxt.js",
    "remix": "Remix",
    "gatsby": "Gatsby",
    "astro": "Astro",
    "solidjs": "SolidJS",
    "htmx": "HTMX",
    "alpine.js": "Alpine.js",
    "tailwind": "Tailwind CSS",
    "tailwindcss": "Tailwind CSS",
    "bootstrap": "Bootstrap",
    "material ui": "Material UI",
    "chakra ui": "Chakra UI",
    "ant design": "Ant Design",
    "shadcn": "shadcn/ui",
    "radix": "Radix UI",
    "storybook": "Storybook",
    # ── CSS & Styling ──
    "html": "HTML",
    "html5": "HTML5",
    "css": "CSS",
    "css3": "CSS3",
    "sass": "SASS",
    "scss": "SCSS",
    "less": "Less",
    "styled components": "Styled Components",
    "postcss": "PostCSS",
    "emotion": "Emotion",
    # ── Backend Frameworks ──
    "fastapi": "FastAPI",
    "django": "Django",
    "flask": "Flask",
    "express": "Express.js",
    "expressjs": "Express.js",
    "nestjs": "NestJS",
    "fastify": "Fastify",
    "koa": "Koa.js",
    "hono": "Hono",
    "spring": "Spring",
    "springboot": "Spring Boot",
    "spring boot": "Spring Boot",
    "rails": "Ruby on Rails",
    "laravel": "Laravel",
    "symfony": "Symfony",
    "gin": "Gin",
    "fiber": "Fiber",
    "actix": "Actix",
    "asp.net": "ASP.NET",
    "blazor": "Blazor",
    ".net": ".NET",
    "dotnet": ".NET",
    "phoenix": "Phoenix",
    "quarkus": "Quarkus",
    "micronaut": "Micronaut",
    "hapi": "Hapi.js",
    # ── Mobile Development ──
    "react native": "React Native",
    "flutter": "Flutter",
    "expo": "Expo",
    "ionic": "Ionic",
    "xamarin": "Xamarin",
    "maui": ".NET MAUI",
    "swiftui": "SwiftUI",
    "jetpack compose": "Jetpack Compose",
    "kotlin multiplatform": "Kotlin Multiplatform",
    "capacitor": "Capacitor",
    # ── Databases ──
    "postgresql": "PostgreSQL",
    "postgres": "PostgreSQL",
    "mysql": "MySQL",
    "mariadb": "MariaDB",
    "mongodb": "MongoDB",
    "redis": "Redis",
    "elasticsearch": "Elasticsearch",
    "cassandra": "Cassandra",
    "dynamodb": "DynamoDB",
    "firestore": "Firestore",
    "sqlite": "SQLite",
    "oracle": "Oracle DB",
    "mssql": "SQL Server",
    "sql server": "SQL Server",
    "neo4j": "Neo4j",
    "influxdb": "InfluxDB",
    "sql": "SQL",
    "nosql": "NoSQL",
    "supabase": "Supabase",
    "firebase": "Firebase",
    "planetscale": "Planetscale",
    "cockroachdb": "CockroachDB",
    "timescaledb": "TimescaleDB",
    "snowflake": "Snowflake",
    "bigquery": "BigQuery",
    "redshift": "Redshift",
    "clickhouse": "ClickHouse",
    # ── Cloud Platforms ──
    "aws": "AWS",
    "amazon web services": "AWS",
    "gcp": "GCP",
    "google cloud": "Google Cloud",
    "azure": "Azure",
    "microsoft azure": "Microsoft Azure",
    "digitalocean": "DigitalOcean",
    "heroku": "Heroku",
    "vercel": "Vercel",
    "netlify": "Netlify",
    "cloudflare": "Cloudflare",
    "huawei cloud": "Huawei Cloud",
    "alibaba cloud": "Alibaba Cloud",
    "aliyun": "Alibaba Cloud",
    "oracle cloud": "Oracle Cloud",
    # ── DevOps & Infrastructure ──
    "docker": "Docker",
    "kubernetes": "Kubernetes",
    "k8s": "Kubernetes",
    "terraform": "Terraform",
    "ansible": "Ansible",
    "helm": "Helm",
    "jenkins": "Jenkins",
    "github actions": "GitHub Actions",
    "gitlab ci": "GitLab CI",
    "gitlab": "GitLab",
    "circleci": "CircleCI",
    "travis": "Travis CI",
    "nginx": "Nginx",
    "apache": "Apache",
    "linux": "Linux",
    "unix": "Unix",
    "ubuntu": "Ubuntu",
    "centos": "CentOS",
    "debian": "Debian",
    "git": "Git",
    "github": "GitHub",
    "bitbucket": "Bitbucket",
    "ci/cd": "CI/CD",
    "cicd": "CI/CD",
    "vagrant": "Vagrant",
    "packer": "Packer",
    "consul": "Consul",
    "istio": "Istio",
    "argocd": "ArgoCD",
    "pulumi": "Pulumi",
    "datadog": "Datadog",
    "newrelic": "New Relic",
    "splunk": "Splunk",
    "cloudformation": "AWS CloudFormation",
    "serverless": "Serverless",
    # ── Data Science & ML ──
    "pandas": "Pandas",
    "numpy": "NumPy",
    "scipy": "SciPy",
    "matplotlib": "Matplotlib",
    "seaborn": "Seaborn",
    "plotly": "Plotly",
    "tensorflow": "TensorFlow",
    "pytorch": "PyTorch",
    "keras": "Keras",
    "scikit-learn": "Scikit-learn",
    "sklearn": "Scikit-learn",
    "xgboost": "XGBoost",
    "lightgbm": "LightGBM",
    "catboost": "CatBoost",
    "huggingface": "Hugging Face",
    "langchain": "LangChain",
    "llamaindex": "LlamaIndex",
    "spark": "Apache Spark",
    "hadoop": "Hadoop",
    "kafka": "Kafka",
    "airflow": "Apache Airflow",
    "dbt": "dbt",
    "mlflow": "MLflow",
    "wandb": "Weights & Biases",
    "dvc": "DVC",
    "streamlit": "Streamlit",
    "gradio": "Gradio",
    "jupyter": "Jupyter",
    "opencv": "OpenCV",
    "pillow": "Pillow",
    # ── Data Visualization & BI ──
    "tableau": "Tableau",
    "powerbi": "Power BI",
    "power bi": "Power BI",
    "looker": "Looker",
    "metabase": "Metabase",
    "google analytics": "Google Analytics",
    "google analytics 4": "Google Analytics 4",
    "ga4": "GA4",
    "adobe analytics": "Adobe Analytics",
    "mixpanel": "Mixpanel",
    "amplitude": "Amplitude",
    # ── AI / ML Concepts ──
    "machine learning": "Machine Learning",
    "deep learning": "Deep Learning",
    "natural language processing": "NLP",
    "nlp": "NLP",
    "computer vision": "Computer Vision",
    "data engineering": "Data Engineering",
    "data science": "Data Science",
    "data analysis": "Data Analysis",
    "data analytics": "Data Analytics",
    "big data": "Big Data",
    "data mining": "Data Mining",
    "reinforcement learning": "Reinforcement Learning",
    "generative ai": "Generative AI",
    "gen ai": "Gen AI",
    "genai": "GenAI",
    "llm": "Large Language Models",
    "large language models": "Large Language Models",
    "rag": "RAG",
    "retrieval augmented generation": "RAG",
    "prompt engineering": "Prompt Engineering",
    "ai agent": "AI Agents",
    "ai agents": "AI Agents",
    "mcp": "MCP",
    "model context protocol": "Model Context Protocol",
    "fine-tuning": "Fine-Tuning",
    "transfer learning": "Transfer Learning",
    "feature engineering": "Feature Engineering",
    "a/b testing": "A/B Testing",
    "ab testing": "A/B Testing",
    # ── API & Architecture ──
    "rest": "REST API",
    "restful": "REST API",
    "rest api": "REST API",
    "grpc": "gRPC",
    "graphql": "GraphQL",
    "websocket": "WebSocket",
    "microservices": "Microservices",
    "event driven": "Event-Driven Architecture",
    "message queue": "Message Queue",
    "soa": "SOA",
    "api gateway": "API Gateway",
    "service mesh": "Service Mesh",
    "event sourcing": "Event Sourcing",
    "cqrs": "CQRS",
    # ── Methodologies ──
    "agile": "Agile",
    "scrum": "Scrum",
    "kanban": "Kanban",
    "devops": "DevOps",
    "mlops": "MLOps",
    "devsecops": "DevSecOps",
    "tdd": "TDD",
    "bdd": "BDD",
    "ddd": "Domain-Driven Design",
    "clean architecture": "Clean Architecture",
    "system design": "System Design",
    "object oriented": "OOP",
    "oop": "OOP",
    "functional programming": "Functional Programming",
    "sprint": "Sprint Planning",
    "waterfall": "Waterfall",
    "prince2": "PRINCE2",
    "six sigma": "Six Sigma",
    "lean": "Lean",
    "itil": "ITIL",
    "sre": "SRE",
    "site reliability engineering": "SRE",
    # ── Project Management & Collaboration ──
    "jira": "Jira",
    "confluence": "Confluence",
    "notion": "Notion",
    "asana": "Asana",
    "trello": "Trello",
    "monday.com": "Monday.com",
    "slack": "Slack",
    "microsoft teams": "Microsoft Teams",
    "linear": "Linear",
    "clickup": "ClickUp",
    "basecamp": "Basecamp",
    "ms project": "MS Project",
    "pmp": "PMP",
    "pmp certification": "PMP",
    "prince2 certification": "PRINCE2",
    "csm": "CSM",
    "safe": "SAFe",
    # ── Design Tools ──
    "figma": "Figma",
    "sketch": "Sketch",
    "adobe xd": "Adobe XD",
    "adobe photoshop": "Adobe Photoshop",
    "photoshop": "Adobe Photoshop",
    "adobe illustrator": "Adobe Illustrator",
    "illustrator": "Adobe Illustrator",
    "adobe after effects": "Adobe After Effects",
    "after effects": "Adobe After Effects",
    "adobe premiere": "Adobe Premiere Pro",
    "premiere pro": "Adobe Premiere Pro",
    "indesign": "Adobe InDesign",
    "canva": "Canva",
    "invision": "InVision",
    "zeplin": "Zeplin",
    "framer": "Framer",
    "miro": "Miro",
    "lucidchart": "Lucidchart",
    "whimsical": "Whimsical",
    "blender": "Blender",
    # ── Testing Tools ──
    "postman": "Postman",
    "swagger": "Swagger",
    "openapi": "OpenAPI",
    "selenium": "Selenium",
    "cypress": "Cypress",
    "playwright": "Playwright",
    "jest": "Jest",
    "vitest": "Vitest",
    "pytest": "pytest",
    "junit": "JUnit",
    "mocha": "Mocha",
    "chai": "Chai",
    "cucumber": "Cucumber",
    "k6": "k6",
    "jmeter": "JMeter",
    "locust": "Locust",
    "pylint": "Pylint",
    "eslint": "ESLint",
    "ruff": "Ruff",
    # ── Messaging & Queuing ──
    "celery": "Celery",
    "rabbitmq": "RabbitMQ",
    "apache pulsar": "Apache Pulsar",
    "amazon sqs": "Amazon SQs",
    "google pub/sub": "Google Pub/Sub",
    # ── Monitoring & Observability ──
    "prometheus": "Prometheus",
    "grafana": "Grafana",
    "sentry": "Sentry",
    "elk stack": "ELK Stack",
    "elastic stack": "Elastic Stack",
    "loki": "Loki",
    "jaeger": "Jaeger",
    "opentelemetry": "OpenTelemetry",
    "zipkin": "Zipkin",
    # ── Security ──
    "cybersecurity": "Cybersecurity",
    "penetration testing": "Penetration Testing",
    "pentesting": "Penetration Testing",
    "owasp": "OWASP",
    "ssl/tls": "SSL/TLS",
    "oauth": "OAuth",
    "jwt": "JWT",
    "sso": "SSO",
    "saml": "SAML",
    "encryption": "Encryption",
    "information security": "Information Security",
    "kali linux": "Kali Linux",
    "burp suite": "Burp Suite",
    "wireshark": "Wireshark",
    "nessus": "Nessus",
    "sonarqube": "SonarQube",
    "sast": "SAST",
    "dast": "DAST",
    # ── ERP & Business Systems ──
    "sap": "SAP",
    "oracle erp": "Oracle ERP",
    "microsoft dynamics": "Microsoft Dynamics",
    "salesforce": "Salesforce",
    "hubspot": "HubSpot",
    "zoho": "Zoho",
    "workday": "Workday",
    "peoplesoft": "PeopleSoft",
    "odoo": "Odoo",
    # ── Marketing & SEO ──
    "seo": "SEO",
    "search engine optimization": "SEO",
    "sem": "SEM",
    "google ads": "Google Ads",
    "google adwords": "Google Ads",
    "facebook ads": "Facebook Ads",
    "meta ads": "Meta Ads",
    "tiktok ads": "TikTok Ads",
    "linkedin ads": "LinkedIn Ads",
    "semrush": "SEMrush",
    "ahrefs": "Ahrefs",
    "moz": "Moz",
    "google search console": "Google Search Console",
    "mailchimp": "Mailchimp",
    "hubspot marketing": "HubSpot Marketing",
    "hootsuite": "Hootsuite",
    "buffer": "Buffer",
    "sprout social": "Sprout Social",
    "social media marketing": "Social Media Marketing",
    "content marketing": "Content Marketing",
    "email marketing": "Email Marketing",
    "inbound marketing": "Inbound Marketing",
    "marketing automation": "Marketing Automation",
    "google tag manager": "Google Tag Manager",
    "gtm": "GTM",
    "conversion rate optimization": "CRO",
    "cro": "CRO",
    # ── E-Commerce & Marketplace (Indonesia) ──
    "shopee": "Shopee",
    "tokopedia": "Tokopedia",
    "lazada": "Lazada",
    "bukalapak": "Bukalapak",
    "blibli": "Blibli",
    "tiktok shop": "TikTok Shop",
    "woocommerce": "WooCommerce",
    "shopify": "Shopify",
    "magento": "Magento",
    "prestashop": "PrestaShop",
    "opencart": "OpenCart",
    "marketplace": "Marketplace",
    "e-commerce": "E-Commerce",
    "ecommerce": "E-Commerce",
    "dropship": "Dropship",
    "dropshipping": "Dropshipping",
    "fulfillment": "Fulfillment",
    "product listing": "Product Listing",
    "catalog management": "Catalog Management",
    "payment gateway": "Payment Gateway",
    "midtrans": "Midtrans",
    "xendit": "Xendit",
    "doku": "DOKU",
    "ovo": "OVO",
    "gopay": "GoPay",
    "dana": "DANA",
    "linkaja": "LinkAja",
    "qris": "QRIS",
    # ── Indonesian Tech Ecosystem ──
    "gojek": "Gojek",
    "grab": "Grab",
    "traveloka": "Traveloka",
    "flip": "Flip",
    "ajaib": "Ajaib",
    "stockbit": "Stockbit",
    "bibit": "Bibit",
    "ruangguru": "Ruangguru",
    "zenius": "Zenius",
    "halodoc": "Halodoc",
    "alodokter": "Alodokter",
    "kumparan": "Kumparan",
    "detik": "Detik.com",
    "kompas": "Kompas",
    # ── Fintech & Banking ──
    "fintech": "Fintech",
    "financial technology": "Fintech",
    "blockchain": "Blockchain",
    "web3": "Web3",
    "cryptocurrency": "Cryptocurrency",
    "smart contract": "Smart Contracts",
    "defi": "DeFi",
    "nft": "NFT",
    "digital banking": "Digital Banking",
    "digital payment": "Digital Payment",
    "e-wallet": "E-Wallet",
    "digital wallet": "Digital Wallet",
    "peer to peer lending": "P2P Lending",
    "p2p lending": "P2P Lending",
    "crowdfunding": "Crowdfunding",
    "insurtech": "Insurtech",
    "regtech": "Regtech",
    # ── Productivity & Office ──
    "microsoft office": "Microsoft Office",
    "ms office": "Microsoft Office",
    "microsoft excel": "Microsoft Excel",
    "excel": "Microsoft Excel",
    "microsoft word": "Microsoft Word",
    "microsoft powerpoint": "Microsoft PowerPoint",
    "powerpoint": "Microsoft PowerPoint",
    "sharepoint": "SharePoint",
    "google workspace": "Google Workspace",
    "gsuite": "Google Workspace",
    "google docs": "Google Docs",
    "google sheets": "Google Sheets",
    "google slides": "Google Slides",
    "spreadsheets": "Spreadsheets",
    # ── Operating Systems ──
    "macos": "macOS",
    "windows": "Windows",
    "windows server": "Windows Server",
    "android": "Android",
    "ios": "iOS",
    # ── Soft Skills ──
    "leadership": "Leadership",
    "team leadership": "Team Leadership",
    "teamwork": "Teamwork",
    "communication": "Communication",
    "communication skills": "Communication Skills",
    "public speaking": "Public Speaking",
    "presentation skills": "Presentation Skills",
    "problem solving": "Problem Solving",
    "critical thinking": "Critical Thinking",
    "analytical thinking": "Analytical Thinking",
    "analytical skills": "Analytical Skills",
    "time management": "Time Management",
    "project management": "Project Management",
    "program management": "Program Management",
    "change management": "Change Management",
    "risk management": "Risk Management",
    "stakeholder management": "Stakeholder Management",
    "conflict resolution": "Conflict Resolution",
    "negotiation": "Negotiation",
    "decision making": "Decision Making",
    "strategic planning": "Strategic Planning",
    "strategic thinking": "Strategic Thinking",
    "business strategy": "Business Strategy",
    "business development": "Business Development",
    "business analysis": "Business Analysis",
    "business intelligence": "Business Intelligence",
    "cross functional": "Cross-Functional Collaboration",
    "cross-functional team": "Cross-Functional Team",
    "client management": "Client Management",
    "client relations": "Client Relations",
    "customer service": "Customer Service",
    "customer success": "Customer Success",
    "customer experience": "Customer Experience",
    "user experience": "User Experience",
    "ux": "UX",
    "ui": "UI",
    "user interface": "User Interface",
    "ux research": "UX Research",
    "user research": "User Research",
    "wireframing": "Wireframing",
    "prototyping": "Prototyping",
    "responsive design": "Responsive Design",
    "design thinking": "Design Thinking",
    "product management": "Product Management",
    "product design": "Product Design",
    "product development": "Product Development",
    "mentoring": "Mentoring",
    "coaching": "Coaching",
    "training": "Training",
    "facilitation": "Facilitation",
    "adaptability": "Adaptability",
    "creativity": "Creativity",
    "innovation": "Innovation",
    "emotional intelligence": "Emotional Intelligence",
    "attention to detail": "Attention to Detail",
    "multitasking": "Multitasking",
    "collaboration": "Collaboration",
    "remote work": "Remote Work",
    "remote collaboration": "Remote Collaboration",
    "continuous learning": "Continuous Learning",
    "self-motivated": "Self-Motivated",
    "empathy": "Empathy",
    "interpersonal skills": "Interpersonal Skills",
    "organizational skills": "Organizational Skills",
    "work under pressure": "Work Under Pressure",
    # ── Finance & Accounting ──
    "financial analysis": "Financial Analysis",
    "financial modeling": "Financial Modeling",
    "financial reporting": "Financial Reporting",
    "financial planning": "Financial Planning",
    "budgeting": "Budgeting",
    "budget management": "Budget Management",
    "forecasting": "Forecasting",
    "accounting": "Accounting",
    "auditing": "Auditing",
    "taxation": "Taxation",
    "payroll": "Payroll",
    "invoicing": "Invoicing",
    "bookkeeping": "Bookkeeping",
    "gaap": "GAAP",
    "psak": "PSAK",
    "ifrs": "IFRS",
    "cash flow": "Cash Flow Management",
    "cost analysis": "Cost Analysis",
    "revenue growth": "Revenue Growth",
    "portfolio management": "Portfolio Management",
    "investment analysis": "Investment Analysis",
    "due diligence": "Due Diligence",
    "compliance": "Compliance",
    "regulatory compliance": "Regulatory Compliance",
    "risk assessment": "Risk Assessment",
    # ── HR & People ──
    "human resources": "Human Resources",
    "hr": "Human Resources",
    "recruitment": "Recruitment",
    "talent acquisition": "Talent Acquisition",
    "talent management": "Talent Management",
    "performance management": "Performance Management",
    "employee engagement": "Employee Engagement",
    "onboarding": "Onboarding",
    "learning and development": "Learning & Development",
    "l&d": "Learning & Development",
    "organizational development": "Organizational Development",
    "compensation and benefits": "Compensation & Benefits",
    "employee relations": "Employee Relations",
    "succession planning": "Succession Planning",
    # ── Operations & Supply Chain ──
    "operations management": "Operations Management",
    "supply chain": "Supply Chain",
    "supply chain management": "Supply Chain Management",
    "logistics": "Logistics",
    "procurement": "Procurement",
    "vendor management": "Vendor Management",
    "inventory management": "Inventory Management",
    "warehouse management": "Warehouse Management",
    "quality assurance": "Quality Assurance",
    "qa": "QA",
    "quality control": "Quality Control",
    "qc": "QC",
    "process improvement": "Process Improvement",
    "continuous improvement": "Continuous Improvement",
    "lean six sigma": "Lean Six Sigma",
    "iso": "ISO",
    "iso 9001": "ISO 9001",
    "sop": "SOP",
    "standard operating procedures": "Standard Operating Procedures",
    # ── Education & Training ──
    "teaching": "Teaching",
    "curriculum development": "Curriculum Development",
    "e-learning": "E-Learning",
    "instructional design": "Instructional Design",
    "learning management system": "LMS",
    "lms": "LMS",
    "moodle": "Moodle",
    "canvas lms": "Canvas LMS",
    # ── Healthcare ──
    "healthcare": "Healthcare",
    "telemedicine": "Telemedicine",
    "medical coding": "Medical Coding",
    "clinical data": "Clinical Data",
    "hipaa": "HIPAA",
    "patient care": "Patient Care",
    "nursing": "Nursing",
    "pharmaceutical": "Pharmaceutical",
    # ── Legal & Compliance ──
    "legal": "Legal",
    "contract management": "Contract Management",
    "litigation": "Litigation",
    "corporate law": "Corporate Law",
    "intellectual property": "Intellectual Property",
    "data privacy": "Data Privacy",
    "gdpr": "GDPR",
    "pdpa": "PDPA",
    "pdp law": "PDP Law (Indonesia)",
    # ── Indonesia-Specific Certifications ──
    "bnsp": "BNSP Certification",
    "tuk": "TUK Certification",
    "lsp": "LSP Certification",
    "kominfo": "Kominfo Certification",
    "cloud practitioner": "AWS Cloud Practitioner",
    "aws solutions architect": "AWS Solutions Architect",
    "aws certified": "AWS Certified",
    "azure fundamentals": "Azure Fundamentals",
    "gcp certified": "GCP Certified",
    "google certified": "Google Certified",
    "scrum master": "Scrum Master",
    "product owner": "Product Owner",
    "togaf": "TOGAF",
    # ── Content & Media ──
    "content writing": "Content Writing",
    "copywriting": "Copywriting",
    "technical writing": "Technical Writing",
    "graphic design": "Graphic Design",
    "video editing": "Video Editing",
    "video production": "Video Production",
    "photography": "Photography",
    "photo editing": "Photo Editing",
    "social media": "Social Media",
    "social media management": "Social Media Management",
    "digital marketing": "Digital Marketing",
    "content strategy": "Content Strategy",
    "brand management": "Brand Management",
    "branding": "Branding",
    "public relations": "Public Relations",
    "pr": "Public Relations",
    "journalism": "Journalism",
    "editing": "Editing",
    "publishing": "Publishing",
    "podcast": "Podcast Production",
    # ── Networking & Infrastructure ──
    "networking": "Networking",
    "cisco": "Cisco",
    "ccna": "CCNA",
    "ccnp": "CCNP",
    "dns": "DNS",
    "vpn": "VPN",
    "lan": "LAN",
    "wan": "WAN",
    "tcp/ip": "TCP/IP",
    "firewall": "Firewall",
    "load balancing": "Load Balancing",
    "cdn": "CDN",
    # ── Version Control & Build ──
    "webpack": "Webpack",
    "vite": "Vite",
    "babel": "Babel",
    "rollup": "Rollup",
    "esbuild": "esbuild",
    "parcel": "Parcel",
    "turbopack": "Turbopack",
    "npm": "npm",
    "yarn": "Yarn",
    "pnpm": "pnpm",
    "bun": "Bun",
    "pip": "pip",
    "conda": "Conda",
    "poetry": "Poetry",
    "uv": "uv",
    "maven": "Maven",
    "gradle": "Gradle",
    "nuget": "NuGet",
    # ── CMS & Platforms ──
    "wordpress": "WordPress",
    "drupal": "Drupal",
    "contentful": "Contentful",
    "strapi": "Strapi",
    "sanity": "Sanity",
    "webflow": "Webflow",
    "squarespace": "Squarespace",
    "wix": "Wix",
    "elementor": "Elementor",
    # ── Other In-Demand Skills ──
    "sustainability": "Sustainability",
    "esg": "ESG",
    "green technology": "Green Technology",
    "digital transformation": "Digital Transformation",
    "automation": "Automation",
    "rpa": "RPA",
    "robotic process automation": "RPA",
    "power automate": "Power Automate",
    "zapier": "Zapier",
    "n8n": "n8n",
    "make": "Make (Integromat)",
    "low-code": "Low-Code",
    "no-code": "No-Code",
    "iot": "IoT",
    "internet of things": "IoT",
    "embedded systems": "Embedded Systems",
    "arduino": "Arduino",
    "raspberry pi": "Raspberry Pi",
    "game development": "Game Development",
    "unity": "Unity",
    "unreal engine": "Unreal Engine",
    "godot": "Godot",
    "3d modeling": "3D Modeling",
    "vr": "VR",
    "ar": "AR",
    "augmented reality": "Augmented Reality",
    "virtual reality": "Virtual Reality",
    "metaverse": "Metaverse",
    # ── Food & Beverage ──
    "barista": "Barista",
    "latte art": "Latte Art",
    "coffee brewing": "Coffee Brewing",
    "coffee roasting": "Coffee Roasting",
    "coffee tasting": "Coffee Tasting",
    "cupping": "Coffee Cupping",
    "espresso": "Espresso Preparation",
    "brewing": "Brewing",
    "bartending": "Bartending",
    "mixology": "Mixology",
    "cocktail making": "Cocktail Making",
    "bartender": "Bartender",
    "sommelier": "Sommelier",
    "wine tasting": "Wine Tasting",
    "food preparation": "Food Preparation",
    "food handling": "Food Handling",
    "food safety": "Food Safety",
    "food safety certification": "Food Safety Certification",
    "food presentation": "Food Presentation",
    "food processing": "Food Processing",
    "food production": "Food Production",
    "baking": "Baking",
    "pastry": "Pastry",
    "baking skills": "Baking Skills",
    "cake decorating": "Cake Decorating",
    "butchery": "Butchery",
    "meal preparation": "Meal Preparation",
    "menu planning": "Menu Planning",
    "menu development": "Menu Development",
    "recipe development": "Recipe Development",
    "catering": "Catering",
    "meal planning": "Meal Planning",
    "kitchen management": "Kitchen Management",
    "kitchen equipment": "Kitchen Equipment",
    "commercial kitchen": "Commercial Kitchen",
    "cooking": "Cooking",
    "chef": "Chef",
    "sous chef": "Sous Chef",
    "head chef": "Head Chef",
    "line cook": "Line Cook",
    "prep cook": "Prep Cook",
    "pastry chef": "Pastry Chef",
    "haccp": "HACCP",
    "halal certification": "Halal Certification",
    "bpom": "BPOM",
    "fnb": "F&B",
    "f&b": "F&B",
    "food and beverage": "Food & Beverage",
    "restaurant management": "Restaurant Management",
    "cafe management": "Cafe Management",
    "coffee shop": "Coffee Shop Management",
    # ── Retail & Store Operations ──
    "retail": "Retail",
    "retail management": "Retail Management",
    "store management": "Store Management",
    "store operations": "Store Operations",
    "store crew": "Store Crew",
    "sales associate": "Sales Associate",
    "cashier": "Cashier",
    "cash handling": "Cash Handling",
    "pos system": "POS System",
    "point of sale": "Point of Sale",
    "visual merchandising": "Visual Merchandising",
    "merchandising": "Merchandising",
    "inventory control": "Inventory Control",
    "stock management": "Stock Management",
    "stocktaking": "Stocktaking",
    "shelf stocking": "Shelf Stocking",
    "customer support": "Customer Support",
    "customer relations": "Customer Relations",
    "upselling": "Upselling",
    "cross-selling": "Cross-Selling",
    "sales target": "Sales Target",
    "sales report": "Sales Reporting",
    "opening closing": "Opening/Closing Procedures",
    "shift management": "Shift Management",
    "retail sales": "Retail Sales",
    "product knowledge": "Product Knowledge",
    # ── Hospitality & Tourism ──
    "hospitality": "Hospitality",
    "hotel management": "Hotel Management",
    "front office": "Front Office",
    "front desk": "Front Desk",
    "receptionist": "Receptionist",
    "reservations": "Reservations",
    "concierge": "Concierge",
    "housekeeping": "Housekeeping",
    "room service": "Room Service",
    "laundry service": "Laundry Service",
    "guest relations": "Guest Relations",
    "guest service": "Guest Service",
    "guest satisfaction": "Guest Satisfaction",
    "hotel operations": "Hotel Operations",
    "banquet": "Banquet Operations",
    "banquet operations": "Banquet Operations",
    "event planning": "Event Planning",
    "event management": "Event Management",
    "event organizer": "Event Organizer",
    "event coordination": "Event Coordination",
    "wedding organizer": "Wedding Organizer",
    "wo": "Wedding Organizer",
    "wedding planning": "Wedding Planning",
    "venue management": "Venue Management",
    "event setup": "Event Setup",
    "stage management": "Stage Management",
    "sound system": "Sound System",
    "lighting design": "Lighting Design",
    "audio visual": "Audio Visual",
    "tour guide": "Tour Guide",
    "tourism": "Tourism",
    "travel agent": "Travel Agent",
    "travel planning": "Travel Planning",
    "travel management": "Travel Management",
    "tour operations": "Tour Operations",
    "ticketing": "Ticketing",
    "booking system": "Booking System",
    "reservation system": "Reservation System",
    "hospitality management": "Hospitality Management",
    "spa management": "Spa Management",
    "massage therapy": "Massage Therapy",
    "beauty therapy": "Beauty Therapy",
    "hair styling": "Hair Styling",
    "makeup artist": "Makeup Artist",
    "makeup": "Makeup Artistry",
    "grooming": "Grooming",
    "salon management": "Salon Management",
    "barber": "Barber",
    # ── Waitstaff & Service ──
    "waiter": "Waiter",
    "waitress": "Waitress",
    "server": "Server (F&B)",
    "table service": "Table Service",
    "food service": "Food Service",
    "silver service": "Silver Service",
    "order taking": "Order Taking",
    "serving": "Serving",
    "plate service": "Plate Service",
    "buffet service": "Buffet Service",
    # ── Manufacturing & Production ──
    "manufacturing": "Manufacturing",
    "production": "Production",
    "production planning": "Production Planning",
    "production management": "Production Management",
    "production line": "Production Line",
    "assembly line": "Assembly Line",
    "machine operation": "Machine Operation",
    "machine operator": "Machine Operator",
    "cnc": "CNC Machining",
    "cnc machining": "CNC Machining",
    "cnc programming": "CNC Programming",
    "cnc machine": "CNC Machine",
    "lathe": "Lathe Operation",
    "milling": "Milling",
    "grinding": "Grinding",
    "drilling": "Drilling",
    "cutting": "Cutting",
    "welding": "Welding",
    "mig welding": "MIG Welding",
    "tig welding": "TIG Welding",
    "arc welding": "Arc Welding",
    "soldering": "Soldering",
    "fabrication": "Fabrication",
    "sheet metal": "Sheet Metal Work",
    "metalworking": "Metalworking",
    "casting": "Casting",
    "molding": "Molding",
    "injection molding": "Injection Molding",
    "plc": "PLC Programming",
    "plc programming": "PLC Programming",
    "scada": "SCADA",
    "hmi": "HMI",
    "industrial automation": "Industrial Automation",
    "robotics": "Robotics",
    "robot programming": "Robot Programming",
    "mechatronics": "Mechatronics",
    "lean manufacturing": "Lean Manufacturing",
    "kaizen": "Kaizen",
    "5s": "5S",
    "poka-yoke": "Poka-Yoke",
    "value stream mapping": "Value Stream Mapping",
    "root cause analysis": "Root Cause Analysis",
    "corrective action": "Corrective Action",
    "preventive maintenance": "Preventive Maintenance",
    "maintenance": "Maintenance",
    "troubleshooting": "Troubleshooting",
    "calibration": "Calibration",
    "blueprint reading": "Blueprint Reading",
    "technical drawing": "Technical Drawing",
    "cad": "CAD",
    "autocad": "AutoCAD",
    "solidworks": "SolidWorks",
    "catia": "CATIA",
    "revit": "Revit",
    "bim": "BIM",
    "cnc operator": "CNC Operator",
    "plc troubleshooting": "PLC Troubleshooting",
    "safety procedures": "Safety Procedures",
    "occupational safety": "Occupational Safety",
    "k3": "K3 (Keselamatan Kerja)",
    "k3 umum": "K3 Umum",
    "smk3": "SMK3",
    "p2k3": "P2K3",
    "ahli k3": "Ahli K3",
    "tkd": "TKD (Tenaga Kerja Harian)",
    "tkwl": "TKWL",
    "operator": "Operator",
    "teknisi": "Teknisi",
    "mekanik": "Mekanik",
    "electrician": "Electrician",
    "panel listrik": "Panel Listrik",
    # ── Construction & Trades ──
    "construction": "Construction",
    "construction management": "Construction Management",
    "carpentry": "Carpentry",
    "carpenter": "Carpenter",
    "woodworking": "Woodworking",
    "joinery": "Joinery",
    "plumbing": "Plumbing",
    "plumber": "Plumber",
    "pipe fitting": "Pipe Fitting",
    "pipefitting": "Pipefitting",
    "electrical work": "Electrical Work",
    "electrical wiring": "Electrical Wiring",
    "electrical installation": "Electrical Installation",
    "masonry": "Masonry",
    "bricklaying": "Bricklaying",
    "concrete work": "Concrete Work",
    "concrete": "Concrete Work",
    "reinforcement": "Reinforcement",
    "rebar": "Rebar Installation",
    "formwork": "Formwork",
    "scaffolding": "Scaffolding",
    "roofing": "Roofing",
    "tiling": "Tiling",
    "flooring": "Flooring",
    "painting": "Painting",
    "painter": "Painter",
    "plastering": "Plastering",
    "drywall": "Drywall Installation",
    "insulation": "Insulation",
    "glazing": "Glazing",
    "landscaping": "Landscaping",
    "excavation": "Excavation",
    "demolition": "Demolition",
    "renovation": "Renovation",
    "building inspection": "Building Inspection",
    "structural analysis": "Structural Analysis",
    "site management": "Site Management",
    "project site": "Project Site",
    "surveying": "Surveying",
    "land surveying": "Land Surveying",
    "total station": "Total Station",
    "heavy equipment": "Heavy Equipment",
    "heavy machinery": "Heavy Machinery",
    "crane operation": "Crane Operation",
    "forklift": "Forklift",
    "forklift operator": "Forklift Operator",
    "excavator": "Excavator",
    "bulldozer": "Bulldozer",
    "tower crane": "Tower Crane",
    "boiler": "Boiler Operation",
    "generator": "Generator Operation",
    "welding inspection": "Welding Inspection",
    "ndt": "NDT (Non-Destructive Testing)",
    "non-destructive testing": "Non-Destructive Testing",
    # ── Agriculture & Farming ──
    "agriculture": "Agriculture",
    "farming": "Farming",
    "agribusiness": "Agribusiness",
    "agronomy": "Agronomy",
    "crop management": "Crop Management",
    "crop production": "Crop Production",
    "harvesting": "Harvesting",
    "planting": "Planting",
    "irrigation": "Irrigation",
    "irrigation system": "Irrigation System",
    "soil analysis": "Soil Analysis",
    "soil management": "Soil Management",
    "pest management": "Pest Management",
    "pest control": "Pest Control",
    "fertilizer application": "Fertilizer Application",
    "animal husbandry": "Animal Husbandry",
    "livestock": "Livestock Management",
    "poultry": "Poultry Farming",
    "aquaculture": "Aquaculture",
    "fisheries": "Fisheries",
    "fish farming": "Fish Farming",
    "dairy farming": "Dairy Farming",
    "horticulture": "Horticulture",
    "floriculture": "Floriculture",
    "hydroponics": "Hydroponics",
    "aeroponics": "Aeroponics",
    "greenhouse": "Greenhouse Management",
    "greenhouse management": "Greenhouse Management",
    "plant breeding": "Plant Breeding",
    "seed production": "Seed Production",
    "organic farming": "Organic Farming",
    "precision agriculture": "Precision Agriculture",
    "smart farming": "Smart Farming",
    "agricultural machinery": "Agricultural Machinery",
    "tractor operation": "Tractor Operation",
    "combine harvester": "Combine Harvester",
    "sawmill": "Sawmill Operations",
    "forestry": "Forestry",
    "plantation": "Plantation Management",
    "palm oil": "Palm Oil",
    "kelapa sawit": "Kelapa Sawit",
    "karet": "Karet (Rubber)",
    "rubber plantation": "Rubber Plantation",
    "padi": "Padi (Rice)",
    "rice farming": "Rice Farming",
    "cocoa": "Cocoa",
    "coffee farming": "Coffee Farming",
    "kopi": "Kopi (Coffee)",
    "teh": "Teh (Tea)",
    "tea plantation": "Tea Plantation",
    "tebu": "Tebu (Sugarcane)",
    "lesson planning": "Lesson Planning",
    "classroom management": "Classroom Management",
    "student assessment": "Student Assessment",
    "educational technology": "Educational Technology",
    "edtech": "EdTech",
    "special education": "Special Education",
    "early childhood education": "Early Childhood Education",
    "ecl": "Early Childhood Education",
    "paud": "PAUD",
    "tk": "TK (Taman Kanak-Kanak)",
    "sd": "SD (Sekolah Dasar)",
    "smp": "SMP (Sekolah Menengah Pertama)",
    "sma": "SMA (Sekolah Menengah Atas)",
    "smk": "SMK (Sekolah Menengah Kejuruan)",
    "online learning": "Online Learning",
    "distance learning": "Distance Learning",
    "google classroom": "Google Classroom",
    "zoom": "Zoom",
    "tutoring": "Tutoring",
    "bimbel": "Bimbel (Bimbingan Belajar)",
    "les privat": "Les Privat",
    "kurikulum merdeka": "Kurikulum Merdeka",
    "telehealth": "Telehealth",
    "clinical research": "Clinical Research",
    "nurse": "Nurse",
    "perawat": "Perawat",
    "bidan": "Bidan",
    "pharmacy": "Pharmacy",
    "apoteker": "Apoteker",
    "laboratory": "Laboratory",
    "lab technician": "Lab Technician",
    "analis kesehatan": "Analis Kesehatan",
    "radiology": "Radiology",
    "physiotherapy": "Physiotherapy",
    "fisioterapi": "Fisioterapi",
    "nutrition": "Nutrition",
    "gizi": "Gizi (Nutrition)",
    "ahli gizi": "Ahli Gizi",
    "first aid": "First Aid",
    "pertolongan pertama": "Pertolongan Pertama",
    "cpr": "CPR",
    "medical equipment": "Medical Equipment",
    "electronic health record": "EHR",
    "medical record": "Medical Record",
    "rekam medis": "Rekam Medis",
    "bpjs": "BPJS",
    "bpjs kesehatan": "BPJS Kesehatan",
    "puskesmas": "Puskesmas",
    "rsud": "RSUD",
    "rumah sakit": "Rumah Sakit",
    "kesehatan masyarakat": "Kesehatan Masyarakat",
    "keselamatan pasien": "Keselamatan Pasien",
    "infection control": "Infection Control",
    "pengendalian infeksi": "Pengendalian Infeksi",
    "mental health": "Mental Health",
    "psikologi": "Psikologi",
    "psychology": "Psychology",
    "counseling": "Counseling",
    "konseling": "Konseling",
    # ── Transportation & Logistics ──
    "transportation": "Transportation",
    "distribution": "Distribution",
    "fleet management": "Fleet Management",
    "fleet maintenance": "Fleet Maintenance",
    "driver": "Driver",
    "supir": "Supir",
    "pengemudi": "Pengemudi",
    "ojol": "Ojol (Ojek Online)",
    "ojek online": "Ojek Online",
    "taxi driver": "Taxi Driver",
    "truk": "Truk",
    "truck driver": "Truck Driver",
    "pengiriman": "Pengiriman",
    "delivery": "Delivery",
    "last mile delivery": "Last Mile Delivery",
    "courier": "Courier",
    "kurir": "Kurir",
    "cargo": "Cargo",
    "freight": "Freight",
    "shipping": "Shipping",
    "customs clearance": "Customs Clearance",
    "import export": "Import/Export",
    "ekspor impor": "Ekspor Impor",
    "warehouse": "Warehouse",
    "warehousing": "Warehousing",
    "picking packing": "Picking & Packing",
    "order fulfillment": "Order Fulfillment",
    "cold chain": "Cold Chain",
    "cold storage": "Cold Storage",
    "route planning": "Route Planning",
    "gps tracking": "GPS Tracking",
    "armada": "Armada",
    "manajemen armada": "Manajemen Armada",
    # ── Creative & Media ──
    "creative writing": "Creative Writing",
    "desain grafis": "Desain Grafis",
    "videography": "Videography",
    "foto": "Fotografi",
    "photographer": "Photographer",
    "content creation": "Content Creation",
    "humas": "Hubungan Masyarakat",
    "jurnalisme": "Jurnalisme",
    "reporter": "Reporter",
    "wartawan": "Wartawan",
    "podcast production": "Podcast Production",
    "live streaming": "Live Streaming",
    "broadcasting": "Broadcasting",
    "animation": "Animation",
    "animasi": "Animasi",
    "illustration": "Illustration",
    "ilustrasi": "Ilustrasi",
    "music production": "Music Production",
    "audio editing": "Audio Editing",
    "sound design": "Sound Design",
    "voice over": "Voice Over",
    "dubbing": "Dubbing",
    "mc": "MC (Master of Ceremony)",
    "hosting": "Hosting (MC)",
    "moderator": "Moderator",
    "influencer marketing": "Influencer Marketing",
    "content creator": "Content Creator",
    "kreator konten": "Kreator Konten",
    "selebriti online": "Seleb Online",
    # ── Beauty & Wellness ──
    "beautician": "Beautician",
    "kecantikan": "Kecantikan",
    "skin care": "Skin Care",
    "skincare": "Skincare",
    "facial treatment": "Facial Treatment",
    "manicure": "Manicure",
    "pedicure": "Pedicure",
    "nail art": "Nail Art",
    "kuku": "Nail Art",
    "aromatherapy": "Aromatherapy",
    "reflexology": "Reflexology",
    "wellness": "Wellness",
    "fitness": "Fitness",
    "personal trainer": "Personal Trainer",
    "yoga": "Yoga",
    "pilates": "Pilates",
    "gym": "Gym/Fitness",
    "instruktur fitness": "Instruktur Fitness",
    # ── Domestic & Care Work ──
    "childcare": "Childcare",
    "pengasuh anak": "Pengasuh Anak",
    "baby sitter": "Babysitter",
    "babysitter": "Babysitter",
    "elder care": "Elder Care",
    "perawat lansia": "Perawat Lansia",
    "caregiver": "Caregiver",
    "home care": "Home Care",
    "household management": "Household Management",
    "art": "ART (Asisten Rumah Tangga)",
    "asisten rumah tangga": "Asisten Rumah Tangga",
    "pembantu": "Pembantu Rumah Tangga",
    "cleaning": "Cleaning",
    "cleaning service": "Cleaning Service",
    "janitorial": "Janitorial",
    "laundry": "Laundry",
    "ironing": "Ironing",
    "masak": "Memasak",
    # ── Security & Safety ──
    "security": "Security",
    "satpam": "Satpam",
    "security guard": "Security Guard",
    "pengamanan": "Pengamanan",
    "cctv monitoring": "CCTV Monitoring",
    "access control": "Access Control",
    "patrol": "Security Patrol",
    "bodyguard": "Bodyguard",
    "safety officer": "Safety Officer",
    "fire safety": "Fire Safety",
    "keselamatan kerja": "Keselamatan Kerja",
    "first responder": "First Responder",
    "emergency response": "Emergency Response",
    "penanggulangan bencana": "Penanggulangan Bencana",
    # ── Driver & Delivery (Indonesia) ──
    "sim a": "SIM A",
    "sim b": "SIM B",
    "sim c": "SIM C",
    "surat izin mengemudi": "SIM",
    "driver ojol": "Driver Ojek Online",
    "gojek driver": "Gojek Driver",
    "grab driver": "Grab Driver",
    "maxim driver": "Maxim Driver",
    "shopee driver": "Shopee Driver",
    "tokopedia driver": "Tokopedia Driver",
    "antar jemput": "Antar Jemput",
    "angkot": "Angkot",
    "bus driver": "Bus Driver",
    "bus akap": "Bus AKAP",
    "travel driver": "Travel Driver",
    # ── Admin & Clerical ──
    "administrative": "Administrative",
    "administrative support": "Administrative Support",
    "admin": "Admin",
    "data entry": "Data Entry",
    "filing": "Filing",
    "document management": "Document Management",
    "record keeping": "Record Keeping",
    "clerical": "Clerical",
    "office management": "Office Management",
    "secretary": "Secretary",
    "sekretaris": "Sekretaris",
    "executive assistant": "Executive Assistant",
    "personal assistant": "Personal Assistant",
    "office administration": "Office Administration",
    "correspondence": "Correspondence",
    "scheduling": "Scheduling",
    "appointment scheduling": "Appointment Scheduling",
    "phone etiquette": "Phone Etiquette",
    "telephone skills": "Telephone Skills",
    "mail handling": "Mail Handling",
    "scanning": "Document Scanning",
    "typing": "Typing",
    "typing speed": "Typing Speed",
    "surat menyurat": "Surat Menyurat",
    "arsip": "Pengarsipan",
    "pengarsipan": "Pengarsipan",
    "nota dinas": "Nota Dinas",
    "surat tugas": "Surat Tugas",
    # ── Sales & Marketing ──
    "sales": "Sales",
    "penjualan": "Penjualan",
    "direct sales": "Direct Sales",
    "field sales": "Field Sales",
    "telesales": "Telesales",
    "telemarketing": "Telemarketing",
    "inside sales": "Inside Sales",
    "b2b sales": "B2B Sales",
    "b2c sales": "B2C Sales",
    "account executive": "Account Executive",
    "account manager": "Account Manager",
    "lead generation": "Lead Generation",
    "cold calling": "Cold Calling",
    "prospecting": "Prospecting",
    "closing": "Closing",
    "customer relationship management": "CRM",
    "crm": "CRM",
    "pipeline management": "Pipeline Management",
    "territory management": "Territory Management",
    "key account management": "Key Account Management",
    "canvassing": "Canvassing",
    "sales promotion": "Sales Promotion",
    "sales reporting": "Sales Reporting",
    "market research": "Market Research",
    "competitor analysis": "Competitor Analysis",
    "customer insights": "Customer Insights",
    # ── Property & Real Estate ──
    "real estate": "Real Estate",
    "property management": "Property Management",
    "property development": "Property Development",
    "broker properti": "Broker Properti",
    "agen properti": "Agen Properti",
    "marketing properti": "Marketing Properti",
    "appraisal": "Property Appraisal",
    "kpr": "KPR",
    "kredit kepemilikan rumah": "KPR",
    "notaris": "Notaris",
    "ajb": "AJB",
    "sertifikat tanah": "Sertifikat Tanah",
    # ── Garment & Textile ──
    "garment": "Garment",
    "textile": "Textile",
    "textile industry": "Textile Industry",
    "sewing": "Sewing",
    "menjahit": "Menjahit",
    "tailor": "Tailor",
    "penjahit": "Penjahit",
    "pattern making": "Pattern Making",
    "pola busana": "Pola Busana",
    "fashion design": "Fashion Design",
    "desain busana": "Desain Busana",
    "fashion": "Fashion",
    "sample making": "Sample Making",
    "konveksi": "Konveksi",
    "garmen": "Garmen",
    # ── Automotive ──
    "automotive": "Automotive",
    "otomotif": "Otomotif",
    "car repair": "Car Repair",
    "bengkel": "Bengkel",
    "mekanik mobil": "Mekanik Mobil",
    "auto repair": "Auto Repair",
    "engine repair": "Engine Repair",
    "tire service": "Tire Service",
    "body repair": "Body Repair",
    "car maintenance": "Car Maintenance",
    "servis mobil": "Servis Mobil",
    "oil change": "Oil Change",
    "vehicle inspection": "Vehicle Inspection",
    "dealership": "Dealership",
    "motorcycle": "Motorcycle",
    "sepeda motor": "Sepeda Motor",
    "mekanik motor": "Mekanik Motor",
    # ── Mining & Energy ──
    "mining": "Mining",
    "pertambangan": "Pertambangan",
    "coal mining": "Coal Mining",
    "tambang batu bara": "Tambang Batu Bara",
    "mineral processing": "Mineral Processing",
    "exploration": "Mineral Exploration",
    "geology": "Geology",
    "geologi": "Geologi",
    "geothermal": "Geothermal",
    "energi terbarukan": "Energi Terbarukan",
    "renewable energy": "Renewable Energy",
    "solar panel": "Solar Panel",
    "surya": "Energi Surya",
    "energy management": "Energy Management",
    "oil and gas": "Oil & Gas",
    "migas": "Migas",
    "refinery": "Refinery",
    "pertamina": "Pertamina",
    "pln": "PLN",
    "listrik": "Kelistrikan",
    "power plant": "Power Plant",
    "pembangkit listrik": "Pembangkit Listrik",
    # ── Marine & Fishery ──
    "maritime": "Maritime",
    "kelautan": "Kelautan",
    "perikanan": "Perikanan",
    "nelayan": "Nelayan",
    "fishing": "Fishing",
    "kapal": "Kapal",
    "pelabuhan": "Pelabuhan",
    "kapal laut": "Kapal Laut",
    "navigation": "Navigation",
    "navigasi": "Navigasi",
    "ahli nautika": "Ahli Nautika",
    # ── Public Service & Government ──
    "public service": "Public Service",
    "pelayanan publik": "Pelayanan Publik",
    "government": "Government",
    "pemerintah": "Pemerintah",
    "asn": "ASN",
    "pns": "PNS",
    "pppk": "PPPK",
    "aparatur sipil negara": "ASN",
    "kepegawaian": "Kepegawaian",
    "administrasi pemerintahan": "Administrasi Pemerintahan",
    "perencanaan pembangunan": "Perencanaan Pembangunan",
    "kebijakan publik": "Kebijakan Publik",
    "public policy": "Public Policy",
    "perundang-undangan": "Perundang-Undangan",
    "osp": "OSP",
    "organization development": "Organization Development",
    # ── Insurance ──
    "insurance": "Insurance",
    "asuransi": "Asuransi",
    "life insurance": "Life Insurance",
    "asuransi jiwa": "Asuransi Jiwa",
    "health insurance": "Health Insurance",
    "asuransi kesehatan": "Asuransi Kesehatan",
    "underwriting": "Underwriting",
    "claims processing": "Claims Processing",
    "aktuaris": "Aktuaris",
    "actuarial": "Actuarial Science",
}


_WHITELIST_LOWER: dict[str, str] = {k.lower(): v for k, v in _SKILLS_WHITELIST.items()}


_MAX_NGRAM = max(len(k.split()) for k in _SKILLS_WHITELIST)


def extract_skills(text: str, score_cutoff: int = 85) -> list[str]:
    nlp = get_nlp()
    doc = nlp(text)

    tokens = [token.text for token in doc if not token.is_space]
    matched: set[str] = set()
    covered: set[int] = set()

    for ngram_len in range(_MAX_NGRAM, 0, -1):
        for i in range(len(tokens) - ngram_len + 1):

            if any(j in covered for j in range(i, i + ngram_len)):
                continue
            phrase = " ".join(tokens[i : i + ngram_len]).lower().strip(".,;:()")
            if phrase in _WHITELIST_LOWER:
                matched.add(_WHITELIST_LOWER[phrase])
                for j in range(i, i + ngram_len):
                    covered.add(j)

    if _FUZZY_AVAILABLE and score_cutoff > 0:
        _fuzzy_match_uncovered(tokens, covered, matched, score_cutoff)

    logger.info("skill_extraction_done", count=len(matched))
    return sorted(matched)


def _fuzzy_match_uncovered(
    tokens: list[str],
    covered: set[int],
    matched: set[str],
    score_cutoff: int,
) -> None:
    for ngram_len in range(min(_MAX_NGRAM, 3), 1, -1):
        for i in range(len(tokens) - ngram_len + 1):
            if any(j in covered for j in range(i, i + ngram_len)):
                continue
            phrase = " ".join(tokens[i : i + ngram_len]).lower().strip(".,;:()")
            best_score = 0.0
            best_match: str | None = None
            for key, display in _WHITELIST_LOWER.items():
                if abs(len(key.split()) - ngram_len) > 1:
                    continue
                score = _fuzz.ratio(phrase, key)
                if score > best_score:
                    best_score = score
                    best_match = display
            if best_score >= score_cutoff and best_match:
                matched.add(best_match)
                for j in range(i, i + ngram_len):
                    covered.add(j)
                break
