"""add_workspace_draft_to_jobs

Revision ID: f9f23d731d78
Revises: 2f7cea2fde5e
Create Date: 2026-04-11 22:10:25.750001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f9f23d731d78'
down_revision: Union[str, None] = '2f7cea2fde5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('workspace_draft', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # knowledge_chunks_embedding_idx intentionally excluded — hnsw vector index managed separately
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'workspace_draft')
    # ### end Alembic commands ###
