"""add nlp jsonb columns to jobs

Revision ID: c16445cc89d8
Revises: 4999d9d2f445
Create Date: 2026-04-05 22:02:25.373194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c16445cc89d8'
down_revision: Union[str, None] = '4999d9d2f445'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('nlp_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('jobs', sa.Column('scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('jobs', sa.Column('grammar_issues', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('jobs', sa.Column('ats_checks', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'ats_checks')
    op.drop_column('jobs', 'grammar_issues')
    op.drop_column('jobs', 'scores')
    op.drop_column('jobs', 'nlp_result')
    # ### end Alembic commands ###
