name: Enable PR Auto-merge

on:
  pull_request_target:
    branches:
      - "main"
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  enable-auto-merge:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: merge